//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FederalTimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTimeSheet
    {
        public int AuditTimeSheetId { get; set; }
        public TimeSheetStatus Status { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int TimeSheetTimeSheetId { get; set; }
    
        public virtual TimeSheet TimeSheet { get; set; }
    }
}
