//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FederalTimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.MyProjects = new HashSet<MyProject>();
            this.TimeSheets = new HashSet<TimeSheet>();
            this.Salaries = new HashSet<Salary>();
        }
    
        public int EmployeeId { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Title { get; set; }
        public Role Role { get; set; }
        public EmployeeType EmployeeType { get; set; }
        public string EmailID { get; set; }
        public bool Active { get; set; }
        public Nullable<int> ReportingTo { get; set; }
        public string SAMAccountName { get; set; }
        public string Note { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<MyProject> MyProjects { get; set; }
        public virtual ICollection<TimeSheet> TimeSheets { get; set; }
        public virtual ICollection<Salary> Salaries { get; set; }
        public virtual Employee ReportingManager { get; set; }
    }
}
