//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FederalTimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyProject
    {
        public int MyProjectId { get; set; }
        public int EmployeeEmployeeId { get; set; }
        public int ProjectProjectId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
