//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FederalTimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectYearEO
    {
        public int ProjectYearEOId { get; set; }
        public string EOCode { get; set; }
        public string ProjectName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Note { get; set; }
        public int ProjectProjectId { get; set; }
        public int FYearFYearId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual FYear FYear { get; set; }
    }
}
