//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FederalTimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public TimeSheet()
        {
            this.TimeEntries = new HashSet<TimeEntry>();
            this.AuditTimeSheets = new HashSet<AuditTimeSheet>();
        }
    
        public int TimeSheetId { get; set; }
        public short Year { get; set; }
        public short Month { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public string EmployeeComments { get; set; }
        public string ReviewerComments { get; set; }
        public string Signature { get; set; }
        public int FYearFYearId { get; set; }
        public int EmployeeEmployeeId { get; set; }
        public TimeSheetStatus Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual FYear FYear { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<TimeEntry> TimeEntries { get; set; }
        public virtual ICollection<AuditTimeSheet> AuditTimeSheets { get; set; }
    }
}
